############################################################################################################
# 
# Makefile listing all the steps required to regenerate the study/analysis of: -
#   1. Orange data set
#   2. Average monthly temperature analysis land temperatures.
# 
# License: GPL (General Public License)
# Authors: Charles McCann
#          Dominique Edwards
#          Hari Narayan Sanadhya
#          Huynh vu
# Date:    2017/04/22
# 
# Description:
# ------------
# The purpose of this makefile is to provide all the steps to regenerate the study aimed for:
#   1. Analysis of trunk circumferences for different size of the Trees (Builtin data set - Orange)
#   2. Comparitive average monthly temperature analysis of various countries, cities throughout the world 
#       and also for US land temperatures. This includes downloading, tidying and merging data and followed 
#       by the code for preforming the analysis on the data.
# 
# Usage:
# ------
# 1. Copy the Makefile to your program directory.
# 2. Type make to start building your program.
#
# Make Target:
# ------------
# The Makefile provides the following targets to make:
#   $ make clean              Removes all the files that will be created by this process
#   $ make tidy_temp          Cleans/tidies the raw temperature data file(Temp.csv) and stores the tidy file in the data folder
#   $ make tidy_city_temp     Cleans/tidies the raw city temperature data file(CityTemp.csv) and stores the tidy file in the data folder
#   $ make report_orange.md   Using the built-in data set Orange in R, study trunk circumferences for different sizes and groups of the Trees.
#   $ make report_temp.md     Using the tidied temperature and city temperature data, perform certain data analytics process to 
#                               meaningful results from average monthly temperature measures for countries and cities accross the world..
#   $ make install            Install all the required packages used within this project (doBy, ggplot2, dplyr and lubridate)
#   $ make all                Perform all the above make targets except install with a single command execution

install: source/install_package.r
	Rscript $<
	
all: clean tidy_temp tidy_city_temp report_orange report_temp

# Remove all the files generated by this process
clean:
	rm -f data/cleaned_City_Temp_Data.txt data/difference_of_average_US_land_temperature_by_year.txt data/cleaned_Temp_Data.txt data/max_variation_in_monthly_avg_temp_by_country.txt graphs/'Average US land temperature by year.png' graphs/'Maximum Temp Variation-City.png' graphs/'Maximum Temp Variation.png' graphs/'Scatter plot of circumference vs age.png' graphs/'Boxplot of circumference by tree.png'

# Call the r script that will generate tidy temperature file - data/cleaned_Temp_Data.txt
tidy_temp: source/tidy_temp.R
	Rscript $<

# Call the r script that will generate tidy city temp file - data/cleaned_City_Temp_Data.txt
tidy_city_temp: source/tidy_city_temp.R
	Rscript $<

# Call the r script that will use the data analytics tools to analyze the Orange data set aiming to study trunk circumferences for different sizes and groups of the Trees.
report_orange: report_orange.Rmd 
	Rscript -e 'rmarkdown::render("$<")'
	
# Call the r script that will use the data analytics tools to analyze the country and city monthly average temperature data
report_temp: report_temp.Rmd 
	Rscript -e 'rmarkdown::render("$<")'
	
